#!/usr/bin/env python
import time
import mailer

import os
from mako.template import Template

from wkhtmltopdf import WKhtmlToPdf
def generate_report(report):
    print "report: %r" % (report,)

    abs_path = os.path.join('reports', '{}.html.mako'.format(report['report']))

    if os.path.exists(abs_path):
        source = Template(filename=abs_path).render(report=report)
    else:
        source = "<h1>There is no report</h1>"

    # TODO: create the tmp directory
    html_file = os.path.join('tmp', "{}.html".format(report['uuid']))
    pdf_file = os.path.join('tmp', "{}.pdf".format(report['uuid']))

    # TODO: Remove the temporary file
    with open(html_file, 'w') as fp:
        fp.write(source)

    wkhtmltopdf = WKhtmlToPdf(html_file, pdf_file)
    wkhtmltopdf.render()

    action = report.get('action', None)
    if action and 'smtp' in action:

        smtp_config = action['smtp']

        message = mailer.Message(From=smtp_config['from'],
                                 To=smtp_config['to'],
                                 Subject=smtp_config['subject'])

        message.Body = """This Report has been generated by printus"""
        message.attach(pdf_file)

        sender = mailer.Mailer('smtp.brutele.be')
        sender.send(message)

    return True
